spring:
  profiles:
    active: dev
  application:
    name: SCM
  #Mysql configurations
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

#Email configurations

